"""One-off cleanup: remove a stray duplicate of invoice 903108957122.

On 2026-06-09 an AI/unknown-carrier extraction fallback ran on this invoice's
PDF and wrote it a second time under a garbled carrier string
("PostNord Sverige AB" instead of "PostNord"), duplicating its cost in every
KPI/timeline that sums by invoice. The real invoice already exists correctly
under carrier="PostNord" (run 20260602_110755_99a67274, corrected date in the
2026-07-07 date backfill). This removes the duplicate header row, its
associated lines/surcharges/checks (all sharing run_id
20260609_152404_d5640e1c), and the one anomaly row generated by that same
mis-extraction (empty run_id, carrier="PostNord Sverige AB", invoice
903108957122, timestamp 2026-06-09T15:51:13) — but NOT the unrelated
DuplicateInvoiceNumber Info anomaly from 2026-07-07 (that one is a correct,
current, harmless log entry), nor the other stale "UnknownCarrier" anomaly
rows for different invoices from that same 2026-06-09 batch (out of scope —
flagged separately, not touched here).

Safe to delete after running once.
"""
import csv
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DASHBOARD_DATA = PROJECT_ROOT / "02_Output" / "Dashboard_Data"
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

DUP_RUN_ID = "20260609_152404_d5640e1c"


def _rewrite(path: Path, keep_row):
    backup = path.with_suffix(".csv.bak2")
    shutil.copy2(path, backup)
    with open(path, encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f, delimiter=";")
        fieldnames = reader.fieldnames
        rows = list(reader)
    kept = [r for r in rows if keep_row(r)]
    removed = len(rows) - len(kept)
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter=";")
        writer.writeheader()
        writer.writerows(kept)
    print(f"{path.name}: removed {removed} row(s), {len(kept)} remain (backup: {backup.name})")


def main():
    _rewrite(DASHBOARD_DATA / "invoice_header.csv",
              lambda r: r.get("run_id") != DUP_RUN_ID)
    _rewrite(DASHBOARD_DATA / "invoice_lines.csv",
              lambda r: r.get("run_id") != DUP_RUN_ID)
    _rewrite(DASHBOARD_DATA / "surcharge_lines.csv",
              lambda r: r.get("run_id") != DUP_RUN_ID)
    _rewrite(DASHBOARD_DATA / "invoice_checks.csv",
              lambda r: r.get("run_id") != DUP_RUN_ID)

    def keep_anomaly(r):
        is_stray = (
            r.get("run_id", "") == ""
            and r.get("processed_timestamp") == "2026-06-09T15:51:13"
            and r.get("carrier") == "PostNord Sverige AB"
            and r.get("invoice_number") == "903108957122"
            and r.get("anomaly_type") == "UnknownCarrier"
        )
        return not is_stray

    _rewrite(DASHBOARD_DATA / "anomalies.csv", keep_anomaly)


if __name__ == "__main__":
    main()
